# pill_train_config.yaml

# 모델 아키텍처 및 입력 크기
architecture: yolo11n
input_size: 1280

# 학습 하이퍼파라미터
epochs: 300
batch_size: 16
learning_rate: 0.001
device: cuda # 또는 cpu

# Early Stopping
patience: 50

# 데이터 경로 (YOLO.train()의 data 인자로 사용될 파일)
data_yaml_path: data.yaml

# 데이터 증강 하이퍼파라미터 (선택 사항)
# 0.0이면 비활성화, 1.0이면 항상 적용
mosaic: 1.0
hsv_h: 0
hsv_s: 0
#hsv_v: 0
#degrees: 180